name: Build PR
on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "temurin"
          cache: 'gradle'

      - name: prebuild 
        run: sed -i -e '/secureProperties/d' build.gradle && echo -e "android.useAndroidX=true\nandroid.enableJetifier=true" > gradle.properties

      - name: Build debug APK and run jvm tests
        run: ./gradlew build
        env:
          PULL_REQUEST: 'true'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/universal/debug/*.apk
